spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/todo
    username: postgres
    password: 123456
    driverClassName: org.postgresql.Driver

server:
  error:
    whitelabel:
      enabled: false

logging:
  level:
    org:
      springframework: debug